title: "[0주차] 2024-10-00 Scrum Meeting 일지"
body:
  - type: markdown
    attributes:
      value: |
        <details>
        <summary>목차</summary>
        <div markdown="1">

        - [회의 진행 내역](#--------)
        - [내일 할일](#-----)

        </div>
        </details>

        ---

        # 회의 진행 내역

        ## 진행 사항
        | 팀원   | 완료                                   | 진행 중                         |
        |-------|---------------------------------------|-------------------------------|
        | 장현   | -                                     | -                             |
        | 정규   | -                                     | -                             |
        | 건우   | -                                     | -                             |
        | 누리   | -                                     | -                             |
        | 문순   | -                                     | -                             |
        | 보호   | -                                     | -                             |
        | 경민   | -                                     | -                             |
        | 용택   | -                                     | -                             |

        ## 회의 내용
        - 객체 규칙
          - dto 객체 이름은 [기능]Request.java 로 이름 짓기 (확정) 
        - custom 예외는 runtimeException가 아닌  globalExceptionHandler.java 를 상속 받아서 사용하기 (Runtime)
        - 명세서 swagger

        ---

        # 내일 할일
        >[!NOTE]
        > - [ ] 내일 할 일이 있다면 적습니다.

        ---

        # 참고
        ## 역할
        | 카테고리         | 팀원                    |
        |----------------|------------------------|
        | **Book**       | 경민, 장현, 정규형         |
        | **Security**   | 서재 주인장, 프로텍션, 택스, 문순쿤 |
        | **CI/CD**      | 건우쿤                  |
        | **주문/결제**    | 택스, 서재 주인장          |
        | **장바구니**     | 문순쿤, 프로텍션           |
        | **쿠폰**        | 장현, 경민               |
        | **포인트/검색**   | 건우쿤, 정규형            |
  - type: input
    id: name
    attributes:
      label: 작성자
